### ISSUE TITLE
.ex files are opened as euphoria3

### ISSUE THREAD

**Issue by evserykh** [elixir-lang/vim-elixir#121]
.ex files are open as euphoria3

**Comment by hafizio** [comment]
The same thing is happening to me, @evserykh how do you solve that?

**Comment by evserykh** [comment]
@hafizio I didn't have any solution ☹

**Comment by kassio** [comment]
can you give us more information, vim version? plugins you're using? etc...

**Comment by evserykh** [comment]
@hafizio I find dirty solution: place these lines into .vimrc
```
au BufRead,BufNewFile *.ex,*.exs set filetype=elixir
au BufRead,BufNewFile *.eex set filetype=eelixir
```

In generally it should be done here
https://github.com/elixir-lang/vim-elixir/blob/master/ftdetect/eelixir.vim#L1
and here 
https://github.com/elixir-lang/vim-elixir/blob/master/ftdetect/elixir.vim#L1
but it doesn't work

**Comment by evserykh** [comment]
@kassio my Vim's version is 7.4.922 and I use a bunch of plugins (https://github.com/evserykh/vimfiles)

Now my .vimrc looks like this
```
Bundle 'elixir-lang/vim-elixir'
" dirty hack
au BufRead,BufNewFile *.ex,*.exs set filetype=elixir
au BufRead,BufNewFile *.eex set filetype=eelixir
```

Maybe is because of 
```
" Euphoria 3 or 4
au BufNewFile,BufRead *.eu,*.ew,*.ex,*.exu,*.exw  call s:EuphoriaCheck()
if has("fname_case")
   au BufNewFile,BufRead *.EU,*.EW,*.EX,*.EXU,*.EXW  call s:EuphoriaCheck()
endif
```
from https://github.com/vim/vim/blob/60cce2fb736c8ff6fdb9603f502d3c15f1f7a25d/runtime/filetype.vim#L548-L552

**Comment by kassio** [comment]
@evserykh do you use any plugin manager on your vim? Plug, Neobundle or something like that?

**Comment by evserykh** [comment]
Yes, I do. I use [Vundle](https://github.com/VundleVim/Vundle.vim)

**Comment by kassio** [comment]
I tried with last version of vim, last version of the plugin and vundle:

**vim version**
```console
$ vim --version
VIM - Vi IMproved 7.4 (2013 Aug 10, compiled Jan 10 2016 11:15:59)
MacOS X (unix) version
Included patches: 1-1076
Compiled by Homebrew
Huge version without GUI.  Features included (+) or not (-):
+acl             +farsi           +mouse_netterm   +syntax
+arabic          +file_in_path    +mouse_sgr       +tag_binary
+autocmd         +find_in_path    -mouse_sysmouse  +tag_old_static
-balloon_eval    +float           +mouse_urxvt     -tag_any_white
-browse          +folding         +mouse_xterm     -tcl
++builtin_terms  -footer          +multi_byte      +terminfo
+byte_offset     +fork()          +multi_lang      +termresponse
+cindent         -gettext         -mzscheme        +textobjects
-clientserver    -hangul_input    +netbeans_intg   +title
+clipboard       +iconv           +path_extra      -toolbar
+cmdline_compl   +insert_expand   +perl            +user_commands
+cmdline_hist    +jumplist        +persistent_undo +vertsplit
+cmdline_info    +keymap          +postscript      +virtualedit
+comments        +langmap         +printer         +visual
+conceal         +libcall         +profile         +visualextra
+cryptv          +linebreak       +python          +viminfo
+cscope          +lispindent      -python3         +vreplace
+cursorbind      +listcmds        +quickfix        +wildignore
+cursorshape     +localmap        +reltime         +wildmenu
+dialog_con      +lua             +rightleft       +windows
+diff            +menu            +ruby            +writebackup
+digraphs        +mksession       +scrollbind      -X11
-dnd             +modify_fname    +signs           -xfontset
-ebcdic          +mouse           +smartindent     -xim
+emacs_tags      -mouseshape      -sniff           -xsmp
+eval            +mouse_dec       +startuptime     -xterm_clipboard
+ex_extra        -mouse_gpm       +statusline      -xterm_save
+extra_search    -mouse_jsbterm   -sun_workshop    -xpm
```

**simplified vimrc**
```viml
set nocompatible              " be iMproved, required
filetype off                  " required

" set the runtime path to include Vundle and initialize
set rtp+=~/.vim/bundles/Vundle.vim
call vundle#begin()

Plugin 'VundleVim/Vundle.vim'
Plugin 'elixir-lang/vim-elixir'

call vundle#end()            " required
filetype plugin indent on    " required
```

But I wasn't able to replicate the error:
![ex](https://cloud.githubusercontent.com/assets/120483/12221671/1916055a-b78c-11e5-9814-d8ecf7e4d90e.gif)

**Comment by evserykh** [comment]
I have the same behavior with your simplified vimrc. 
I''ll try later to comment used plugins one by one and find the guilty one.

**Comment by kassio** [comment]
We just changed the way we set the filetype (#103), can you update and try again?

**Comment by evserykh** [comment]
I updated the plugin and have again euphoria3 file type for *.ex files and empty for *.exs

**Comment by kassio** [comment]
That's sad. I guess you'll need to check all your plugins to find if someone it's breaking the vim-elixir `setf`. If you need any help please let me know.

**Comment by evserykh** [comment]
I installed Vim also using Homebrew. Maybe you can fast try https://github.com/evserykh/vimfiles?
Here is a list of used plugins https://github.com/evserykh/vimfiles/blob/master/vundle.vim.
I'll try later to find out what's going on. 

Thanks for help

**Comment by evserykh** [comment]
I updated my vimfiles repo. It seems the issue has gone now.

Thanks a lot @kassio @igas

**Comment by hackling** [comment]
I'm sadly having this issue as well.

I've rebuilt neovim via homebrew, and I've got the latest version of `vim-elixir`

I'm using Vundle to manage my plugins,
and I'm on the latest version of Neovim `0.1.1`

I've tried stripping everything out of my .vimrc, and still no luck

```
" Required by Vundle
set nocompatible
let mapleader = ","

set rtp+=~/.vim/bundle/vundle/
call vundle#rc()

filetype plugin indent on " Required by Vundle

" Wildmenu
set wildmenu
set wildmode=longest,full

" Search
set ignorecase " Case insensitive search
set incsearch  " Makes search act like search in modern browsers
set hlsearch   " Highlight search results

" Whitespace
set listchars=tab:▸\ ,trail:· " Show tabs, trailing whitespace and end of lines
set nowrap                    " Do not wrap lines
set expandtab                 " Use spaces instead of tabs
set smarttab                  " Be smart when using tabs ;-)
set softtabstop=2             " 1 tab is 2 spaces
set shiftwidth=2
set tabstop=2
set foldmethod=indent         " Fold based on indentation.
set foldlevelstart=99         " Expand all folds by default.
set backspace=2

" Disable backup. No swap files.
set nobackup
set nowb
set noswapfile

" Bindings
nnoremap <Leader>/ :noh<CR><ESC>|"                    Clear highlights
map <Leader>sw :w<Cr>

" Window
syntax enable       " Syntax highlighting
set hidden          " Allow hiding buffers with unsaved changes
set number          " Show line numbers
set ruler           " Show cursor position
set spelllang=en_au " Australian English

" Persistent undo
set undofile                " Save undo's after file closes
set undodir=$HOME/.vim/undo " Where to save histories
set undolevels=1000         " How many undos
set undoreload=10000        " Number of lines to save

runtime macros/matchit.vim
Plugin 'elixir-lang/vim-elixir'
```

**Comment by igas** [comment]
@hackling can you try to switch from `call vundle#rc()` to suggested `begin` / `end` from https://github.com/VundleVim/Vundle.vim#quick-start step 3. Especially `filetype off` then `call vundle#begin()` rest and at the end
```
call vundle#end()            " required
filetype plugin indent on    " required
```

**Comment by hackling** [comment]
I've managed to locate the issue.

``` vim

**Comment by thedanotto** [comment]
For me, I needed to remove `call vundle#rc()` and input `call vundle#begin()` and `call vundle#end()`

Adding `syntax enable` didn't do anything for me.

**Comment by GildedHonour** [comment]
what's the solution to this?

**Comment by evserykh** [comment]
@GildedHonour did you try to move `Plugin 'elixir-lang/vim-elixir'` between `call vundle#begin()` and `call vundle#end()`? It should help.
